# Generated by Django 3.1.7 on 2021-05-18 16:54

import computed_property.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HealthData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(1)])),
                ('height', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(1)])),
                ('imc', computed_property.fields.ComputedFloatField(compute_from='calc_imc', editable=False)),
                ('igc', computed_property.fields.ComputedFloatField(compute_from='calc_igc', editable=False)),
            ],
        ),
    ]
