# Generated by Django 3.1.7 on 2021-05-19 11:13

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('healthData', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthdata',
            name='date',
            field=models.DateField(default=datetime.date(2021, 5, 19)),
        ),
        migrations.AddField(
            model_name='healthdata',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='users.user'),
        ),
        migrations.AlterUniqueTogether(
            name='healthdata',
            unique_together={('user', 'date')},
        ),
        migrations.RemoveField(
            model_name='healthdata',
            name='height',
        ),
        migrations.RemoveField(
            model_name='healthdata',
            name='weight',
        ),
    ]
