# Generated by Django 3.1.7 on 2021-06-02 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthdata', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='healthdatadto',
            name='username',
        ),
        migrations.AddField(
            model_name='healthdatadto',
            name='user_id',
            field=models.IntegerField(default=None),
        ),
    ]
