# Generated by Django 3.1.7 on 2021-06-01 10:22

import computed_property.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthData', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthDataDTO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('weight', models.FloatField(default=1)),
                ('height', models.FloatField(default=1)),
                ('imc', models.FloatField(default=1)),
                ('igc', models.FloatField(default=1)),
                ('date', models.DateField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='healthdata',
            options={},
        ),
        migrations.AlterField(
            model_name='healthdata',
            name='height',
            field=computed_property.fields.ComputedFloatField(compute_from='calc_height', default=1, editable=False),
        ),
        migrations.AlterField(
            model_name='healthdata',
            name='igc',
            field=computed_property.fields.ComputedFloatField(compute_from='calc_igc', default=1, editable=False),
        ),
        migrations.AlterField(
            model_name='healthdata',
            name='imc',
            field=computed_property.fields.ComputedFloatField(compute_from='calc_imc', default=1, editable=False),
        ),
        migrations.AlterField(
            model_name='healthdata',
            name='weight',
            field=computed_property.fields.ComputedFloatField(compute_from='calc_weight', default=1, editable=False),
        ),
        migrations.AlterUniqueTogether(
            name='healthdata',
            unique_together=set(),
        ),
    ]
