# Generated by Django 3.1.7 on 2021-05-20 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthData', '0002_auto_20210519_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthdata',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
