# Generated by Django 3.1.7 on 2021-05-20 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('healthData', '0003_auto_20210520_0839'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='healthdata',
            options={'ordering': ['id']},
        ),
    ]
