# Generated by Django 3.1.7 on 2021-05-22 18:54

import computed_property.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('healthData', '0004_auto_20210520_0935'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthdata',
            name='height',
            field=computed_property.fields.ComputedIntegerField(compute_from='calc_height', default=1, editable=False),
        ),
        migrations.AddField(
            model_name='healthdata',
            name='weight',
            field=computed_property.fields.ComputedIntegerField(compute_from='calc_weight', default=1, editable=False),
        ),
    ]
