# Generated by Django 3.1.7 on 2021-03-21 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('mail', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('gender', models.CharField(max_length=200)),
                ('birthdate', models.DateField()),
                ('activitiesdone', models.IntegerField(default=0)),
                ('points', models.IntegerField(default=0)),
                ('level', models.IntegerField(default=0)),
                ('objective', models.CharField(max_length=200)),
                ('weight', models.IntegerField()),
                ('height', models.IntegerField()),
                ('imc', models.IntegerField()),
                ('igc', models.IntegerField()),
            ],
        ),
    ]
