# Generated by Django 3.1.7 on 2021-04-21 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exercises', '0002_remove_exercise_video'),
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Routine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
                ('time', models.CharField(choices=[('P', 'Personalitzable'), ('R', 'Ronda circuits'), ('F', 'Fixat')], default='F', max_length=30)),
                ('categories', models.ManyToManyField(to='categories.Category')),
                ('exercises', models.ManyToManyField(to='exercises.Exercise')),
            ],
        ),
    ]
