version: '3.7'

services:
  app:
    build:
      context: .
    volumes:
      - static_data:/code
    environment:
      - CGO_ENABLED=0
      - ALLOWED_HOSTS=*
      - DEBUG=1
    networks:
      - fithaus
    depends_on:
      - postgres

  proxy:
    build:
      context: proxy
    volumes:
      - static_data:/code/static
    ports:
      - "80:8080"
    networks:
      - fithaus
    depends_on:
      - app

  postgres:
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    networks:
    - fithaus
    ports:
      - "5432:5432"
    restart: unless-stopped

volumes:
  static_data:
  postgres:

networks:
  fithaus:
    driver: bridge