swagger: "2.0"
info:
  description: "Servidor de l'aplicació FitHaus de l'assignatura PES. Aquí podràs trobar operacions per gestionar usuaris del sistema."
  version: "1.0.0"
  title: "SERVIDOR FITHAUS"
  contact:
    email: "fithaus2021@gmail.com"
host: "127.0.0.1:8000"
schemes:
- "https"
- "http"
paths:
  /user:
    post:
      tags:
      - "user"
      summary: "Crear usuari"
      description: "Crear un usuari a la BD, es produeix quan aquest es registra per primer cop"
      operationId: "createUser"
      produces:
      - "application/json"
      parameters:
        - name: "username"
          in: "query"
          type: "string"
          maxLength: 200
        - name: "firstName"
          in: "query"
          type: "string"
          maxLength: 200
        - name: "lastName"
          in: "query"
          type: "string"
          maxLength: 200
        - name: "email"
          in: "query"
          type: "string"
          maxLength: 200
          format: "email"
        - name: "password"
          in: "query"
          type: "string"
          maxLength: 200
          format: "password"
        - name: "gender"
          in: "query"
          type: "string"
          enum: [ M, W, X ]
        - name: "birthdate"
          in: "query"
          type: "string"
          maxLength: 200
          format: "date"
        - name: "activitiesdone"
          in: "query"
          type: "integer"
          default: 0
        - name: "achievements"
          in: "query"
          type: "string"
          maxLength: 200
        - name: "points"
          in: "query"
          type: "integer"
          default: 0
        - name: "level"
          in: "query"
          type: "integer"
          default: 0
        - name: "objective"
          in: "query"
          type: "string"
          maxLength: 200
        - name: "interestcategories"
          in: "query"
          type: "string"
          maxLength: 200
        - name: "weight"
          in: "query"
          type: "integer"
          default: 0
        - name: "height"
          in: "query"
          type: "integer"
          default: 0
        - name: "imc"
          in: "query"
          type: "integer"
          default: 0
        - name: "igc"
          in: "query"
          type: "integer"
          default: 0
      responses:
        "200":
          description: "Operació exitosa"
        "400":
          description: "Usuari ja existeix"

  /user/login:
    get:
      tags:
      - "user"
      summary: "Loggejar usuari"
      description: "Loggeja un usuari <b>existent</b> al sistema"
      operationId: "loginUser"
      produces:
      - "application/json"
      parameters:
      - name: "email"
        in: "query"
        description: "Email de l'usuari"
        required: true
        type: "string"
      - name: "password"
        in: "query"
        description: "Contrasenya de l'usuari"
        required: true
        type: "string"
      responses:
        "200":
          description: "Operació exitosa"
        "400":
          description: "Credencials incorrectes"
  /user/{id}:
    get:
      tags:
      - "user"
      summary: "Obtenir informació de l'usuari"
      description: ""
      operationId: "getUserById"
      produces:
      - "application/json"
      parameters:
      - name: "id"
        in: "path"
        description: "Id de l'usuari"
        required: true
        type: "string"
      responses:
        "200":
          description: "Operació exitosa"
          schema:
            $ref: "#/definitions/User"
        "400":
          description: "Alguna cosa no ha anat bé..."
    patch:
      tags:
      - "user"
      summary: "Actualitzar info d'un usuari"
      description: "Especificar només els camps a actualitzar, sense importar els altres"
      operationId: "updateUser"
      produces:
      - "application/json"
      parameters:
      - name: "id"
        in: "path"
        description: "Id de l'usuari"
        required: true
        type: "string"
      - name: "username"
        in: "query"
        type: "string"
        maxLength: 200
      - name: "firstName"
        in: "query"
        type: "string"
        maxLength: 200
      - name: "lastName"
        in: "query"
        type: "string"
        maxLength: 200
      - name: "email"
        in: "query"
        type: "string"
        maxLength: 200
        format: "email"
      - name: "password"
        in: "query"
        type: "string"
        maxLength: 200
        format: "password"
      - name: "gender"
        in: "query"
        type: "string"
        enum: [ M, W, X ]
      - name: "birthdate"
        in: "query"
        type: "string"
        maxLength: 200
        format: "date"
      - name: "activitiesdone"
        in: "query"
        type: "integer"
        default: 0
      - name: "achievements"
        in: "query"
        type: "string"
        maxLength: 200
      - name: "points"
        in: "query"
        type: "integer"
        default: 0
      - name: "level"
        in: "query"
        type: "integer"
        default: 0
      - name: "objective"
        in: "query"
        type: "string"
        maxLength: 200
      - name: "interestcategories"
        in: "query"
        type: "string"
        maxLength: 200
      - name: "weight"
        in: "query"
        type: "integer"
        default: 0
      - name: "height"
        in: "query"
        type: "integer"
        default: 0
      - name: "imc"
        in: "query"
        type: "integer"
        default: 0
      - name: "igc"
        in: "query"
        type: "integer"
        default: 0
      responses:
        "200":
          description: "Operació exitosa"
        "400":
          description: "Usuari no trobat"
    delete:
     tags:
     - "user"
     summary: "Eliminar usuari"
     description: ""
     operationId: "deleteUser"
     produces:
     - "application/json"
     parameters:
     - name: "id"
       in: "path"
       description: "Id de l'usuari a eliminar"
       required: true
       type: "string"
     responses:
       "200":
         description: "Operació exitosa"
       "404":
         description: "User not found"

  /activities:
    post:
      tags:
        - "activity"
      summary: "Crear activitat"
      description: "Crear una activitat a la BD"
      operationId: "createActivity"
      produces:
        - "application/json"
      parameters:
        - name: "type"
          in: "query"
          type: "string"
          enum: [ E,C ]
        - name: "name"
          in: "query"
          type: "string"
          maxLength: 30
        - name: "description"
          in: "query"
          type: "string"
          maxLength: 200
        - name: "age"
          in: "query"
          type: "string"
          enum: [ K,T,A,E ]
        - name: "difficulty"
          in: "query"
          type: "string"
          enum: [ E,M,H ]
        - name: "categories"
          in: "query"
          type: "string"
      responses:
        "200":
          description: "Operació exitosa"
        "400":
          description: "Activitat ja existeix"
  /activities/{id}:
    get:
      tags:
        - "activity"
      summary: "Obtenir informació de l'activitat"
      description: ""
      operationId: "getActById"
      produces:
        - "application/json"
      parameters:
        - name: "id"
          in: "path"
          description: "Id de l'activitat"
          required: true
          type: "string"
      responses:
        "200":
          description: "Operació exitosa"
          schema:
            $ref: "#/definitions/Activity"
        "400":
          description: "Alguna cosa no ha anat bé..."

  /categories:
    post:
      tags:
        - "category"
      summary: "Crear categoria"
      description: "Crear una categoria a la BD"
      operationId: "createCategory"
      produces:
        - "application/json"
      parameters:
        - name: "category"
          in: "query"
          type: "string"
          enum: [ S,C,Y,E,R,P ]
      responses:
        "200":
          description: "Operació exitosa"
        "400":
          description: "Categoria ja existeix"
  /categories/{id}:
    get:
      tags:
        - "category"
      summary: "Obtenir informació de la categoria"
      description: ""
      operationId: "getCatById"
      produces:
        - "application/json"
      parameters:
        - name: "id"
          in: "path"
          description: "Id de la categoria"
          required: true
          type: "string"
      responses:
        "200":
          description: "Operació exitosa"
          schema:
            $ref: "#/definitions/Category"
        "400":
          description: "Alguna cosa no ha anat bé..."

  /classes:
    post:
      tags:
        - "class"
      summary: "Crear classe"
      description: "Crear una classe a la BD"
      operationId: "createClass"
      produces:
        - "application/json"
      parameters:
        - name: "activity"
          in: "query"
          type: "string"
        - name: "trainer"
          in: "query"
          type: "string"
        - name: "workarea"
          in: "query"
          type: "string"
          enum: [UB,LB,FB,C]
      responses:
        "200":
          description: "Operació exitosa"
        "400":
          description: "Classe ja existeix"
  /classes/{id}:
    get:
      tags:
        - "class"
      summary: "Obtenir informació de la classe"
      description: ""
      operationId: "getClassById"
      produces:
        - "application/json"
      parameters:
        - name: "id"
          in: "path"
          description: "Id de la classe"
          required: true
          type: "string"
      responses:
        "200":
          description: "Operació exitosa"
          schema:
            $ref: "#/definitions/Class"
        "400":
          description: "Alguna cosa no ha anat bé..."

  /exercises:
    post:
      tags:
        - "exercise"
      summary: "Crear exercici"
      description: "Crear un exercici a la BD"
      operationId: "createExercise"
      produces:
        - "application/json"
      parameters:
        - name: "activity"
          in: "query"
          type: "string"
        - name: "muscle"
          in: "query"
          type: "string"
          enum: [ Bi,Tr,Fa,Ch,Sh,Do,Gl,Fe,Qu,Cm,Co]
      responses:
        "200":
          description: "Operació exitosa"
        "400":
          description: "Exercici ja existeix"
  /exercises/{id}:
    get:
      tags:
        - "exercise"
      summary: "Obtenir informació de l'exercici"
      description: ""
      operationId: "getExerById"
      produces:
        - "application/json"
      parameters:
        - name: "id"
          in: "path"
          description: "Id de l'exercici"
          required: true
          type: "string"
      responses:
        "200":
          description: "Operació exitosa"
          schema:
            $ref: "#/definitions/Exercise"
        "400":
          description: "Alguna cosa no ha anat bé..."

  /objectives:
    post:
      tags:
        - "objective"
      summary: "Crear objectiu"
      description: "Crear un objectiu a la BD"
      operationId: "createObjective"
      produces:
        - "application/json"
      parameters:
        - name: "objective"
          in: "query"
          type: "string"
          enum: [ S,Fr,P,Fl,Rs,Rc,A ]
      responses:
        "200":
          description: "Operació exitosa"
        "400":
          description: "Objectiu ja existeix"
  /objectives/{id}:
    get:
      tags:
        - "objective"
      summary: "Obtenir informació de l'objectiu"
      description: ""
      operationId: "getObjById"
      produces:
        - "application/json"
      parameters:
        - name: "id"
          in: "path"
          description: "Id de l'objectiu"
          required: true
          type: "string"
      responses:
        "200":
          description: "Operació exitosa"
          schema:
            $ref: "#/definitions/Objective"
        "400":
          description: "Alguna cosa no ha anat bé..."

  /customroutines:
    post:
      tags:
        - "custom routine"
      summary: "Crear rutina personalitzada"
      description: "Crear un rutina personalitzada a la BD, hereta del model routines"
      operationId: "createCustomRoutine"
      produces:
        - "application/json"
      parameters:
        - name: "public"
          in: "query"
          type: "boolean"
        - name: "user"
          in: "query"
          type: "string"
      responses:
        "200":
          description: "Operació exitosa"
        "400":
          description: "Rutina personalitzada ja existeix"
  /customroutines/{id}:
    get:
      tags:
        - "custom routine"
      summary: "Obtenir informació de la rutina personalitzada"
      description: ""
      operationId: "getCustomRoutineById"
      produces:
        - "application/json"
      parameters:
        - name: "id"
          in: "path"
          description: "Id de la rutina personalitzada"
          required: true
          type: "string"
      responses:
        "200":
          description: "Operació exitosa"
          schema:
            $ref: "#/definitions/CustomRoutine"
        "400":
          description: "Alguna cosa no ha anat bé..."

  /predefinedroutines:
    post:
      tags:
        - "predefined routine"
      summary: "Crear rutina predefinida"
      description: "Crear un rutina predefinida a la BD, hereta del model routines"
      operationId: "createCustomRoutine"
      produces:
        - "application/json"
      parameters:
      - name: "age"
        in: "query"
        type: "string"
        enum: [ K,T,A,E ]
      - name: "level"
        in: "query"
        type: "string"
        enum: [ P,I,A ]
      - name: "equipment"
        in: "query"
        type: "string"
        enum: [ W,HM,K,D,B,RB,RL,FR ]
      - name: "objective"
        in: "query"
        type: "string"
      - name: "impact"
        in: "query"
        type: "string"
        enum: [ L,M,H ]
      - name: "image"
        in: "query"
        type: "string"
      - name: "user"
        in: "query"
        type: "integer"
      responses:
        "200":
          description: "Operació exitosa"
        "400":
          description: "Rutina predefinida ja existeix"
  /predefinedroutines/{id}:
    get:
      tags:
        - "predefined routine"
      summary: "Obtenir informació de la rutina predefinida"
      description: ""
      operationId: "getPredefinedRoutineById"
      produces:
        - "application/json"
      parameters:
        - name: "id"
          in: "path"
          description: "Id de la rutina predefinida"
          required: true
          type: "string"
      responses:
        "200":
          description: "Operació exitosa"
          schema:
            $ref: "#/definitions/PredefinedRoutine"
        "400":
          description: "Alguna cosa no ha anat bé..."


#securityDefinitions:
 # petstore_auth:
 #   type: "oauth2"
 #   authorizationUrl: "http://petstore.swagger.io/oauth/dialog"
 #   flow: "implicit"
 #   scopes:
 #     write:pets: "modify pets in your account"
 #    read:pets: "read your pets"
 # api_key:
 #   type: "apiKey"
 #   name: "api_key"
 #   in: "header"

definitions:
  User:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      username:
        type: "string"
        maxLength: 200
      firstName:
        type: "string"
        maxLength: 200
      lastName:
        type: "string"
        maxLength: 200
      email:
        type: "string"
        maxLength: 200
        format: "email"
      password:
        type: "string"
        maxLength: 200
        format: "password"
      gender:
        type: "string"
        enum: [M, W, X]
      birthdate:
        type: "string"
        maxLength: 200
        format: "date"
      activitiesdone:
        type: "integer"
        default: 0
      achievements:
        type: "string"
        maxLength: 200
      points:
        type: "integer"
        default: 0
      level:
        type: "integer"
        default: 0
      objective:
        type: "object"
      interestcategories:
        type: "object"
        maxLength: 200
      weight:
        type: "integer"
        default: 0
      height:
        type: "integer"
        default: 0
      imc:
        type: "integer"
        default: 0
      igc:
        type: "integer"
        default: 0

  Activity:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      type:
        type: "string"
        enum: [E,C]
      name:
        type: "string"
        maxLength: 30
      description:
        type: "string"
        maxLength: 200
      age:
        type: "string"
        enum: [K,T,A,E]
      difficulty:
        type: "string"
        enum: [E,M,H]
      length:
        type: "integer"
      categories:
        type: "object"

  Category:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      category:
        type: "string"
        enum: [ S,C,Y,E,R,P ]

  Class:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      activity:
        type: "object"
      trainer:
        type: "string"
        maxLength: 30
      workearea:
        type: "string"
        enum: [ UB,LB,FB,C ]

  Exercise:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      activity:
        type: "object"
      muscle:
        type: "string"
        enum: [ Bi,Tr,Fa,Ch,Sh,Do,Gl,Fe,Qu,Cm,Co ]

  Objective:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      objective:
        type: "string"
        enum: [ S,Fr,P,Fl,Rs,Rc,A ]

  Routine:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      name:
        type: "string"
      description:
        type: "string"
      time:
        type: "string"
        enum: [ P,R,F ]
      categories:
        type: "object"
      exercices:
        type: "object"
      classes:
        type: "object"

  CustomRoutine:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      public:
        type: "boolean"
      user:
        type: "integer"

  PredefinedRoutine:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      age:
        type: "string"
        enum: [ K,T,A,E ]
      level:
        type: "string"
        enum: [ P,I,A ]
      equipment:
        type: "string"
        enum: [ W,HM,K,D,B,RB,RL,FR ]
      objective:
        type: "object"
      impact:
        type: "string"
        enum: [ L,M,H ]
      image:
        type: "string"
      users:
        type: "integer"



  #ApiResponse:
  #  type: "object"
  #  properties:
  #    code:
  #      type: "integer"
  #      format: "int32"
  #    type:
  #      type: "string"
  #    message:
  #      type: "string"
  
