# Generated by Django 3.1.7 on 2021-04-22 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Objective',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objective', models.CharField(choices=[('S', 'Salut'), ('Fr', 'Força'), ('P', 'Perdua'), ('Fl', 'Flexibilitat'), ('Rs', 'Resistencia'), ('Rc', 'Recuperacio'), ('A', 'Agilitat')], default='S', max_length=100, unique=True)),
            ],
        ),
    ]
