# Generated by Django 3.1.7 on 2021-04-21 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activities', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('activity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='class2activity', serialize=False, to='activities.activity')),
                ('trainer', models.CharField(max_length=30)),
                ('workarea', models.CharField(choices=[('UB', 'Upper Body'), ('LB', 'Lower Body'), ('FB', 'Full Body'), ('C', 'Core')], default='FB', max_length=200)),
            ],
        ),
    ]
