# Generated by Django 3.1.7 on 2021-04-22 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trainer', models.CharField(max_length=30)),
                ('workarea', models.CharField(choices=[('UB', 'Upper Body'), ('LB', 'Lower Body'), ('FB', 'Full Body'), ('C', 'Core')], default='FB', max_length=200)),
                ('activity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='class2activity', to='activities.activity')),
            ],
        ),
    ]
