# Generated by Django 3.1.7 on 2021-04-22 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classes',
            name='videoclass',
            field=models.FileField(default=None, upload_to='class_videos'),
        ),
    ]
