# Generated by Django 3.1.7 on 2021-04-21 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_auto_20210421_1652'),
        ('classes', '0004_auto_20210421_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classes',
            name='activity',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='class2activity', serialize=False, to='activities.activity'),
        ),
    ]
