# Generated by Django 3.1.7 on 2021-05-31 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('PredefinedRoutine', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=200)),
                ('predef_routines', models.ManyToManyField(blank=True, to='PredefinedRoutine.PredefinedRoutine')),
            ],
        ),
    ]
