# Generated by Django 3.1.7 on 2021-04-21 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('E', 'Exercise'), ('C', 'Class')], default='E', max_length=30)),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=200)),
                ('age', models.CharField(choices=[('K', 'Kid'), ('T', 'Teenager'), ('A', 'Adult'), ('E', 'Elder')], max_length=30)),
                ('difficulty', models.CharField(choices=[('E', 'Easy'), ('M', 'Medium'), ('H', 'Hard')], max_length=30)),
                ('length', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('activity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='activities.activity')),
                ('trainer', models.CharField(max_length=30)),
                ('workarea', models.CharField(choices=[('UB', 'Upper Body'), ('LB', 'Lower Body'), ('FB', 'Full Body'), ('C', 'Core')], default='FB', max_length=200)),
            ],
            bases=('activities.activity',),
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('activity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='activities.activity')),
                ('video', models.CharField(max_length=2)),
                ('muscle', models.CharField(choices=[('Bi', 'Biceps'), ('Tr', 'Triceps'), ('Fa', 'Forearm'), ('Ch', 'Chest'), ('Sh', 'Shoulder'), ('Do', 'Dorsal'), ('Gl', 'Gluteus'), ('Fe', 'Femoral'), ('Qu', 'Quadriceps'), ('Cm', 'Calf Muscle'), ('Co', 'Core')], default='Bi', max_length=200)),
            ],
            bases=('activities.activity',),
        ),
    ]
