# Generated by Django 3.1.7 on 2021-04-22 07:38

import django.core.files.storage
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('E', 'Exercise'), ('C', 'Class')], default='E', max_length=30)),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=200)),
                ('age', models.CharField(choices=[('K', 'Kid'), ('T', 'Teenager'), ('A', 'Adult'), ('E', 'Elder')], max_length=30)),
                ('difficulty', models.CharField(choices=[('E', 'Easy'), ('M', 'Medium'), ('H', 'Hard')], max_length=30)),
                ('length', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('pre', models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='/images'), upload_to='')),
                ('categories', models.ManyToManyField(to='categories.Category')),
            ],
        ),
    ]
