# Generated by Django 3.1.7 on 2021-05-12 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('CustomRoutine', '0001_initial'),
        ('PredefinedRoutine', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
                ('custom_routines', models.ManyToManyField(blank=True, to='CustomRoutine.CustomRoutine')),
                ('predef_routines', models.ManyToManyField(blank=True, to='PredefinedRoutine.PredefinedRoutine')),
            ],
        ),
    ]
