# Generated by Django 3.1.7 on 2021-04-21 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Objective',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objective', models.CharField(choices=[('S', 'Salut'), ('F', 'Força'), ('P', 'Perdua'), ('F', 'Flexibilitat'), ('RS', 'Resistencia'), ('RC', 'Recuperacio'), ('A', 'Agilitat')], max_length=100)),
            ],
        ),
    ]
