# Generated by Django 3.1.7 on 2021-06-01 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category', models.CharField(choices=[('S', 'Strength'), ('C', 'Cardio'), ('Y', 'Yoga'), ('E', 'Stretching'), ('R', 'Rehabilitation'), ('P', 'Pilates')], max_length=30, primary_key=True, serialize=False)),
            ],
        ),
    ]
