# Generated by Django 3.1.7 on 2021-04-21 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('S', 'Strength'), ('C', 'Cardio'), ('Y', 'Yoga'), ('E', 'Stretching'), ('R', 'Rehabilitation'), ('P', 'Pilates')], default='S', max_length=30)),
                ('activity', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='activities.activity')),
            ],
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(fields=('activity', 'category'), name='parunico'),
        ),
    ]
