# Generated by Django 3.1.7 on 2021-04-21 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activities', '0002_delete_exercise'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('activity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='activities.activity')),
                ('video', models.CharField(max_length=2)),
                ('muscle', models.CharField(choices=[('Bi', 'Biceps'), ('Tr', 'Triceps'), ('Fa', 'Forearm'), ('Ch', 'Chest'), ('Sh', 'Shoulder'), ('Do', 'Dorsal'), ('Gl', 'Gluteus'), ('Fe', 'Femoral'), ('Qu', 'Quadriceps'), ('Cm', 'Calf Muscle'), ('Co', 'Core')], default='Bi', max_length=200)),
            ],
        ),
    ]
