# Generated by Django 3.1.7 on 2021-04-22 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('muscle', models.CharField(choices=[('Bi', 'Biceps'), ('Tr', 'Triceps'), ('Fa', 'Forearm'), ('Ch', 'Chest'), ('Sh', 'Shoulder'), ('Do', 'Dorsal'), ('Gl', 'Gluteus'), ('Fe', 'Femoral'), ('Qu', 'Quadriceps'), ('Cm', 'Calf Muscle'), ('Co', 'Core')], default='Bi', max_length=200)),
                ('activity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='exercise2activity', to='activities.activity')),
            ],
        ),
    ]
