# Generated by Django 3.1.7 on 2021-04-22 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='muscleimage',
            field=models.ImageField(default=None, upload_to='exercise_images'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='videoexercise',
            field=models.FileField(default=None, upload_to='exercise_videos'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='videotutorial',
            field=models.FileField(default=None, upload_to='exercise_videos'),
        ),
    ]
