# Generated by Django 3.1.7 on 2021-06-03 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achievement', models.CharField(choices=[('TT', 'Total Trainings'), ('ST', 'Strength Trainings'), ('CT', 'Cardio Trainings'), ('YT', 'Yoga Trainings'), ('StchT', 'Stretching Trainings'), ('RT', 'Rehabilitation Trainings'), ('PT', 'Pilates Trainings')], max_length=10)),
                ('quantity', models.IntegerField(default=1)),
                ('points', models.IntegerField(default=1)),
            ],
            options={
                'unique_together': {('achievement', 'quantity')},
            },
        ),
    ]
